on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        goversion: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        goversion: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32
    - name: Test
      run: go test ./...
